<?php

namespace SalammouAlikom\IFtarBundle\Repository;

/**
 * iftar_tableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class iftar_tableRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDonatedPersonBy($current_day){

        $qb = $this->createQueryBuilder('d')
            ->select('d')
            ->where('d.startDate >= :current_day')
            ->setParameter('current_day', $current_day);
        return $qb->getQuery()->getResult();
    }
}
