i_ftar:
    resource: "@IFtarBundle/Resources/config/routing.yml"
    prefix:   /



app:
    resource: "@AppBundle/Controller/"
    type:     annotation


fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

# Routing Of FosUserBundle:
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"