i_ftar_homepage:
    path:     /app/index
    defaults: { _controller: IFtarBundle:Default:index }


i_ftar_add_new_donate:
    path:     /app/donates/newdonate
    defaults: { _controller: IFtarBundle:Default:addnewDonate }
    options:
        expose: true

i_ftar_liste_donated_persons:
    path:     /app/donatedpersones
    defaults: { _controller: IFtarBundle:Default:listeAllDonatedPeopleForRamdhan }
    options:
        expose: true

i_ftar_admin_pdf_managment:
    path: app/admin/managmentPdfs
    defaults: { _controller: IFtarBundle:AdminIFtarPage:createTableIFtar}


i_ftar_get_avlaible_data:
    path: app/data
    defaults: { _controller: IFtarBundle:Default:listeMaxData}
    options:
        expose: true

i_ftar_get_prayers:
    path: app/prayers
    defaults: { _controller: IFtarBundle:Prayer:index}

#####################ADMIN####################################
iftar_admin_index:
    path: app/admin
    defaults: { _controller: IFtarBundle:AdminIFtarPage:index}


iftar_admin_update_food:
    path: /app/admin/update/{resource}/{id}/{new_val}
    defaults: { _controller: IFtarBundle:AdminIFtarPage:update }
    options:
        expose: true

iftar_admin_delete_food:
    path: app/admin/delete/{resource}/{id}
    defaults: { _controller: IFtarBundle:AdminIFtarPage:delete }
    options:
        expose: true

#########################AppIFtarRamdathn#########################
app_iftar_ramdathan:
     path: /app
     defaults: { _controller: IFtarBundle:Default:appIndex }